services:
  db:
    image: postgres:18
    container_name: pg18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pg18_data:/var/lib/postgresql

volumes:
  pg18_data:
    external: true
    name: pg18_data
