package com.modernize.contractreplay.contract;

import com.modernize.contractreplay.AbstractContractReplayTest;
import com.modernize.contractreplay.model.ContractResult;
import com.modernize.contractreplay.model.ContractStatus;
import com.modernize.contractreplay.replay.ReplayRun;
import com.modernize.contractreplay.replay.ReplayRunner;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.MethodOrderer.OrderAnnotation;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Verifies the six post-run reconciliation invariants defined in
 * contracts/output/reconciliation-invariants.json after a clean baseline run.
 *
 * Each invariant has its own test so that failures are pinpointed to a single
 * rule — not buried in a compound assertion. The final test asserts the
 * aggregate PASS status across all six invariants.
 *
 * The full suite-level evidence report (all boundaries + all replay scenarios)
 * is generated by SuiteReportTest.
 *
 * All tests use the RP-001 baseline fixture (3 valid records, no rejections)
 * as the pipeline state they check against.
 */
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@TestMethodOrder(OrderAnnotation.class)
class OutputInvariantTest extends AbstractContractReplayTest {

    private static final String BASELINE_FIXTURE = "fixtures/rp-001-baseline.csv";
    private static final String REJECTION_FIXTURE = "fixtures/rp-003-validation-skip.csv";

    private OutputStateInvariantChecker baselineChecker;
    private ReplayRun baselineRun;

    @Override
    protected boolean shouldCleanStateBeforeEach() {
        return false;
    }

    @BeforeAll
    void runBaselinePipelineOnce() throws Exception {
        ReplayRunner.cleanState(jobRepositoryTestUtils, jdbcTemplate);
        baselineRun = ReplayRunner.runFullPipeline(
                jobLauncherTestUtils,
                loadTransactionsJob,
                validateTransactionsJob,
                postTransactionsJob,
                reconcileJob,
                jdbcTemplate,
                BASELINE_FIXTURE);
        baselineChecker = new OutputStateInvariantChecker(jdbcTemplate, baselineRun.batchIds());
    }

    @Test
    @Order(1)
    void inv001_countsMatchShouldBeTrue() {
        ContractResult result = baselineChecker.check();
        assertTrue(
            result.getViolations().stream().noneMatch(v -> v.getRuleId().equals("INV-001")),
            "INV-001 violated: " + result.getViolations());
    }

    @Test
    @Order(2)
    void inv002_totalsMatchShouldBeTrue() {
        ContractResult result = baselineChecker.check();
        assertTrue(
            result.getViolations().stream().noneMatch(v -> v.getRuleId().equals("INV-002")),
            "INV-002 violated: " + result.getViolations());
    }

    @Test
    @Order(3)
    void inv003_stagedCountExcludesRejectedRecords() {
        ContractResult result = baselineChecker.check();
        assertTrue(
            result.getViolations().stream().noneMatch(v -> v.getRuleId().startsWith("INV-003")),
            "INV-003 violated: " + result.getViolations());
    }

    @Test
    @Order(4)
    void inv004_exactlyOneReconRowPerBatch() {
        ContractResult result = baselineChecker.check();
        assertTrue(
            result.getViolations().stream().noneMatch(v -> v.getRuleId().equals("INV-004")),
            "INV-004 violated: " + result.getViolations());
    }

    @Test
    @Order(5)
    void inv005_countsAreNonNegative() {
        ContractResult result = baselineChecker.check();
        assertTrue(
            result.getViolations().stream().noneMatch(v -> v.getRuleId().equals("INV-005")),
            "INV-005 violated: " + result.getViolations());
    }

    @Test
    @Order(6)
    void inv006_postedCountDoesNotExceedStagedCount() {
        ContractResult result = baselineChecker.check();
        assertTrue(
            result.getViolations().stream().noneMatch(v -> v.getRuleId().equals("INV-006")),
            "INV-006 violated: " + result.getViolations());
    }

    /**
     * Aggregate check: all six invariants pass and the overall ContractResult
     * status is PASS. This is a sanity check that the individual tests did not
     * miss a cross-invariant interaction. The full portfolio report (with all
     * boundaries and replay scenarios) is written by SuiteReportTest.
     */
    @Test
    @Order(7)
    void allInvariantsPass() {
        ContractResult result = baselineChecker.check();

        assertEquals(ContractStatus.PASS, result.getOverallStatus(),
            "All invariants should pass after a clean run. Violations: " + result.getViolations());
        assertTrue(result.getViolations().isEmpty(),
            "Expected no violations but got: " + result.getViolations());
    }

    @Test
    @Order(8)
    void inv003_shouldPassWhenRejectedRowsExistButAreExcludedFromCountsAndTotals() throws Exception {
        ReplayRunner.cleanState(jobRepositoryTestUtils, jdbcTemplate);
        ReplayRun rejectionRun = ReplayRunner.runFullPipeline(
            jobLauncherTestUtils,
            loadTransactionsJob,
            validateTransactionsJob,
            postTransactionsJob,
            reconcileJob,
            jdbcTemplate,
            REJECTION_FIXTURE);

        ContractResult result = new OutputStateInvariantChecker(jdbcTemplate, rejectionRun.batchIds()).check();

        assertTrue(result.getViolations().stream().noneMatch(v -> v.getRuleId().equals("INV-003-COUNT")),
            "INV-003-COUNT violated: " + result.getViolations());
        assertTrue(result.getViolations().stream().noneMatch(v -> v.getRuleId().equals("INV-003-TOTAL")),
            "INV-003-TOTAL violated: " + result.getViolations());
    }

    @Test
    @Order(9)
    void inv003_shouldFailWhenStagedTotalCentsIsTampered() throws Exception {
        ReplayRunner.cleanState(jobRepositoryTestUtils, jdbcTemplate);
        ReplayRun tamperedRun = ReplayRunner.runFullPipeline(
            jobLauncherTestUtils,
            loadTransactionsJob,
            validateTransactionsJob,
            postTransactionsJob,
            reconcileJob,
            jdbcTemplate,
            BASELINE_FIXTURE);

        jdbcTemplate.update(
            "UPDATE bank.batch_reconciliations " +
            "SET staged_total_cents = staged_total_cents + 1 " +
            "WHERE batch_id = ?",
            tamperedRun.batchIds().getFirst());

        ContractResult result = new OutputStateInvariantChecker(jdbcTemplate, tamperedRun.batchIds()).check();

        assertTrue(result.getViolations().stream().anyMatch(v -> v.getRuleId().equals("INV-003-TOTAL")),
            "Expected INV-003-TOTAL violation but got: " + result.getViolations());
        assertTrue(result.getViolations().stream().noneMatch(v -> v.getRuleId().equals("INV-003-COUNT")),
            "Expected only the total comparison to fail but got: " + result.getViolations());
    }

    @Test
    @Order(10)
    void scopedChecker_shouldIgnoreHistoricalBadReconciliationsWhenEvaluatingALaterCleanRun() throws Exception {
        ReplayRunner.cleanState(jobRepositoryTestUtils, jdbcTemplate);
        ReplayRun badHistoricalRun = ReplayRunner.runFullPipeline(
            jobLauncherTestUtils,
            loadTransactionsJob,
            validateTransactionsJob,
            postTransactionsJob,
            reconcileJob,
            jdbcTemplate,
            BASELINE_FIXTURE);

        jdbcTemplate.update(
            "UPDATE bank.batch_reconciliations " +
            "SET staged_total_cents = staged_total_cents + 1 " +
            "WHERE batch_id = ?",
            badHistoricalRun.batchIds().getFirst());

        ReplayRun laterCleanRun = ReplayRunner.runFullPipeline(
            jobLauncherTestUtils,
            loadTransactionsJob,
            validateTransactionsJob,
            postTransactionsJob,
            reconcileJob,
            jdbcTemplate,
            BASELINE_FIXTURE);

        ContractResult result = new OutputStateInvariantChecker(jdbcTemplate, laterCleanRun.batchIds()).check();

        assertEquals(ContractStatus.PASS, result.getOverallStatus(),
            "Scoped checker should only evaluate the later clean run: " + result.getViolations());
        assertTrue(result.getViolations().isEmpty(),
            "Historical bad rows should not poison the scoped clean run: " + result.getViolations());
    }
}
