spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/modernize_prod
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

batch-pipeline:
  files:
    - ach_20250310_prod.csv
    - ach_20250317_prod.csv
    - ach_20250324_prod.csv
