name: Maven Test

on:
  pull_request:
    branches: [ main, test ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Make mvnw executable
        run: chmod +x ./app/mvnw

      - name: Run tests
        run: ./app/mvnw -f app/pom.xml test